/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function AsicMiner({ ...props }) {
  const asicRef = useRef()

  useFrame(({clock}) => {
    asicRef.current.rotation.z = clock.getElapsedTime();
  });

  const { nodes, materials } = useGLTF('/nft-clicker-game/asicminerdemo.gltf')
  return (
    <group ref={asicRef} {...props} dispose={null}>
      <mesh geometry={nodes.miner.geometry} material={materials.palette} scale={[0.8, 0.8, 0.8]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}
  
useGLTF.preload('/asicminerdemo.gltf')
